### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by bkj** [shiralkarprashant/knowledgestream#1]
Hi all --

If I run `python setup.py install`, then try to run `kstream`, I get an error like:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "algorithms/mincostflow/ssp.py", line 18, in <module>
    from algorithms.mincostflow.ssp_helper import compute_shortest_path_distances
ImportError: No module named ssp_helper
```

Any thoughts about what might be going on?

Thanks

**Comment by shiralkarprashant** [comment]
Hi,

The installation instructions were missing a line on compilation. I have also fixed a couple import related errors. Please follow the install instructions again, and let me know if there are problems. 

Thanks!

**Comment by shiralkarprashant** [comment]
Assuming this isn't a problem anymore after the previous fix. Closing it for now. Please feel free to reopen if the issue persists. Thanks!
