### ISSUE TITLE
 http://carl.cs.indiana.edu/data/fact-checking/data.zip does not exist

### ISSUE THREAD

**Issue by remember9069** [shiralkarprashant/knowledgestream#10]
Hi, 
I am interested in your model, but the URL given for data downloading no longer exists, could you please re-upload the data.zip or provide the current URL address for downloading?

**Comment by glciampaglia** [comment]
The data were moved to an institutional repository. You can find them at this link:

https://zenodo.org/record/4487154

**Comment by remember9069** [comment]
> The data were moved to an institutional repository. You can find them at this link:
> 
> https://zenodo.org/record/4487154

Got it, thanks for your information.
