### ISSUE TITLE
Implementation methods in this repo on my knowledge graph

### ISSUE THREAD

**Issue by ram7i** [shiralkarprashant/knowledgestream#12]
Hi, I'm interested in implementing some methods on my knowledge graph. When I read that in your paper, 

> relational similarity using TF-IDF representation and cosine similarity.

I'm confused how to get this square matrix which contains 'rel sim' scores. How do you use TF-IDF to count relational weights? 
I guess I need to first construct an adjacency matrix between relations based on my knowledge graph, Could you briefly describe how you do it in code or provide the relevant code?
Thanks in advance, looking forward to your reply

**Comment by shiralkarprashant** [comment]
Hi,

As described in the paper, we create the relational similarity matrix based
on a TF-iDF computation on the co-occurrence matrix of relations in our
knowledge graph.

The code computing this similarity matrix is at
https://github.com/shiralkarprashant/knowledgestream/blob/ca662ec6d4f57d0d776183ff53accb933d470b63/algorithms/relcooc/relsim.py#L102

If you’d like to know how to count the co-occurrence, take a look at this
module:
https://github.com/shiralkarprashant/knowledgestream/blob/master/algorithms/relcooc/relcooc.py

Hope this helps. Let me know if you have any questions.

**Comment by remember9069** [comment]
Thank you for your detailed explanation, now I'll close it, appreciate again.
