### ISSUE TITLE
Data cleaning code

### ISSUE THREAD

**Issue by bkj** [shiralkarprashant/knowledgestream#3]
Is it possible to provide the scripts you used to generate the `.npy` files in `data/kg/_undir`?  They could be useful in trying to apply this repo to additional datasets.

Thanks!

**Comment by filmenczer** [comment]
Looks like this same question was answered in issue #4

**Comment by shiralkarprashant** [comment]
Hope you were able to find and use the script on additional datasets. Closing this issue for now.
