### ISSUE TITLE
Generating .npy files

### ISSUE THREAD

**Issue by siyanapavlova** [shiralkarprashant/knowledgestream#4]
Hi, I would like to run knowledgestream on a few additional datasets and I would very much appreciate if you could share the code to generate the .npy files in data/kg/_undir. Would that be possible?

Thanks!

**Comment by shiralkarprashant** [comment]
Hi, please take a look at https://github.com/shiralkarprashant/knowledgestream/blob/master/datastructures/test_graph.py which has the code to generate those files.

**Comment by shiralkarprashant** [comment]
Hope my comment has helped answer your question by now. Closing this issue. Please feel free to re-open if there are further questions.
